export const colors =  {
  'left field': 'text-[#99ADFF]',
  'acid': 'text-[#F08080]',
  'expirimental': 'text-[#A8FF33]',
  'bass': 'text-[#3386FF]',
  'pop': 'text-[#FF33DD]', 
  'uk funky': 'text-[#BF15E9]',
  'garage': 'text-[#00C85E]',
  'footwerk': 'text-[#FFD134]',
  'electro': 'text-[#34FF8D]',
  'dancehall': 'text-[#FF34A6]',
  'ambient': 'text-[#90FFFD]',
  'jungle': 'text-[#3232FF]',
  'drum and bass': 'text-[#5132FF]',
  'tech house': 'text-[#FFA832]',
  'jazz': 'text-[#2325AD]',
  'disco': 'text-[#C146F6]',
  'dubstep': 'text-[#E6F646]',
  'dub': 'text-[#C3F646]',
  'techno': 'text-[#000000]', 
  'gqom': 'text-[#',
  ']nu wave': 'text-[#00FFF3]',
  'rap': 'text-[#E892FF]',
  'hip hop': 'text-[#AA64BD]',
  'donk': 'text-[#E540DD]',
  'jersey club': 'text-[#F9FF2A]',
  'house': 'text-[#2A2DFF]',
}
export const genres = [
  'acid',
  'ambient',
  'bass',
  'dancehall',
  'disco',
  'donk',
  'drum and bass',
  'dub',
  'dubstep',
  'electro',
  'expirimental',
  'footwerk',
  'garage',
  'gqom',
  'hip hop',
  'house',
  'house',
  'jazz',
  'jersey club',
  'jungle',
  'left field',
  'nu wave',
  'pop',
  'rap',
  'tech house',
  'techno',
  'uk funky',
]