export const colors =  {
  'left field': '#99ADFF',
  'acid': '#F08080',
  'expirimental': '#A8FF33',
  'bass': '#3386FF',
  'pop': '#FF33DD', 
  'uk funky': '#BF15E9',
  'garage': '#00C85E',
  'footwerk': '#FFD134',
  'electro': '#34FF8D',
  'dancehall': '#FF34A6',
  'ambient': '#90FFFD',
  'jungle': '#3232FF',
  'drum and bass': '#5132FF',
  'tech house': '#FFA832',
  'jazz': '#2325AD',
  'disco': '#C146F6',
  'dubstep': '#E6F646',
  'dub': '#C3F646',
  'techno': '#000000', 
  'gqom': '#',
  'nu wave': '#00FFF3',
  'rap': '#E892FF',
  'hip hop': '#AA64BD',
  'donk': '#E540DD',
  'jersey club': '#F9FF2A',
  'house': '#2A2DFF',
}
export const genres = [
  'acid',
  'ambient',
  'bass',
  'dancehall',
  'disco',
  'donk',
  'drum and bass',
  'dub',
  'dubstep',
  'electro',
  'expirimental',
  'footwerk',
  'garage',
  'gqom',
  'hip hop',
  'house',
  'house',
  'jazz',
  'jersey club',
  'jungle',
  'left field',
  'nu wave',
  'pop',
  'rap',
  'tech house',
  'techno',
  'uk funky',
]